// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VemyndStore.Api.Data;

#nullable disable

namespace VemyndStore.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501172357_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VemyndStore.Api.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Connectivity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayResolution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplaySize")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GraphicsCard")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("HasOpticalDrive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsTouchscreen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProcessorGeneration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StorageCapacity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Dell",
                            Connectivity = "Thunderbolt 4, USB 3.2, HDMI, Wi-Fi 6E, Bluetooth 5.2",
                            Description = "Potente notebook com tela InfinityEdge e processador de última geração.",
                            DisplayResolution = "Full HD",
                            DisplaySize = "15.6 polegadas",
                            GraphicsCard = "NVIDIA GeForce RTX 3050",
                            HasOpticalDrive = false,
                            ImageUrl = "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/inspiron-notebooks/15-3520/media-gallery/in3520-xnb-01-bk.psd?fmt=png-alpha&pscan=auto&scl=1&wid=5000&hei=5000&qlt=100,1&resMode=sharp2&size=5000,5000&chrss=full&imwidth=5000",
                            IsTouchscreen = false,
                            Model = "XPS 15",
                            Name = "Notebook Dell XPS 15",
                            OperatingSystem = "Windows 11",
                            Price = 1799.99m,
                            Processor = "Intel Core i7",
                            ProcessorGeneration = "13ª Geração",
                            Ram = "16GB DDR5",
                            ReleaseDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StorageCapacity = "512GB",
                            StorageType = "SSD",
                            Weight = 1.87m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Alienware",
                            Connectivity = "USB 3.2, USB 2.0, Ethernet, Wi-Fi 6, Bluetooth 5.0",
                            Description = "Desktop de alta performance para jogos com design futurista.",
                            DisplayResolution = "",
                            DisplaySize = "",
                            GraphicsCard = "NVIDIA GeForce RTX 3080",
                            HasOpticalDrive = false,
                            ImageUrl = "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/desktops/alienware-desktops/alienware-aurora-r14/media-gallery/dark-side-of-the-moon-bk-clear-panel-clear-air-cooled-air/desktop_alienware_aurora_r14_bk_clear-panel_air_cooled_gallery_3.psd?fmt=png-alpha&pscan=auto&scl=1&wid=2413&hei=3935&qlt=100,1&resMode=sharp2&size=2413,3935&chrss=full&imwidth=5000",
                            IsTouchscreen = false,
                            Model = "Aurora R14",
                            Name = "Desktop Gamer Alienware Aurora R14",
                            OperatingSystem = "Windows 11",
                            Price = 2599.00m,
                            Processor = "AMD Ryzen 9",
                            ProcessorGeneration = "Série 5000",
                            Ram = "32GB DDR4",
                            ReleaseDate = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StorageCapacity = "1TB + 2TB",
                            StorageType = "SSD + HDD",
                            Weight = 12.1m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Lenovo",
                            Connectivity = "USB-C, USB 3.2, HDMI, Wi-Fi 6, Bluetooth 5.1",
                            Description = "Notebook fino e leve para o dia a dia.",
                            DisplayResolution = "Full HD",
                            DisplaySize = "14 polegadas",
                            GraphicsCard = "Intel Iris Xe Graphics",
                            HasOpticalDrive = false,
                            ImageUrl = "https://p3-ofp.static.pub//fes/cms/2024/09/12/5ztqhlpp7ivhmq4rix5lcoyt64hqnz824789.png",
                            IsTouchscreen = false,
                            Model = "IdeaPad Slim 5",
                            Name = "Notebook Lenovo IdeaPad Slim 5",
                            OperatingSystem = "Windows 11",
                            Price = 749.99m,
                            Processor = "Intel Core i5",
                            ProcessorGeneration = "12ª Geração",
                            Ram = "8GB DDR4",
                            ReleaseDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StorageCapacity = "256GB",
                            StorageType = "SSD",
                            Weight = 1.39m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
